services:
  web:
    build: .
    environment:
      - LETSENCRYPT_HOST=exoplanets.jstet.net
      - VIRTUAL_HOST=exoplanets.jstet.net
    restart: unless-stopped
    networks:
    - proxy
    - default
networks:
  proxy:
    external: true

