name: CI

on: 
  push:
    branches:    
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        KEY: ${{ secrets.SSHKEY }}d
        script: |
          cd Exoplanets
          git reset --hard
          git pull origin main
          docker build --no-cache -t localhost:5000/exoplanets .
          docker push localhost:5000/exoplanets
          cd ../compose_exoplanets
          docker stack deploy -c docker-compose.yml exoplanets
